### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by AlexanderSilvaB** [butcherg/DatagramSocket#1]
Hello,

I was looking for a simple class for UDP Socket and I found this one. It is amazing and works perfectly! Using your class I created a new class with support for TCP too. As there's no license in this repository I want to ask if I can publish the new class on GitHub? Giving you the proper credits and mentioning your repository.

Thank you very much for this amazing work!

**Comment by butcherg** [comment]
Alexander,
I may not get to it right away, but I think I'll post the LGPL license to the repository.  You are more than welcome to fork and modify; I'm glad you're finding the class of use.
